// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCexDfLg9_aoPJMoDrIlGHdGyhMobSpZhI',
    appId: '1:1023352143949:web:7ee34888fc4167651d1c04',
    messagingSenderId: '1023352143949',
    projectId: 'untitled-7441b',
    authDomain: 'untitled-7441b.firebaseapp.com',
    storageBucket: 'untitled-7441b.appspot.com',
    measurementId: 'G-MTC8FGJLVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8bK84qGnNGuQrys6fQjFSVYBddjgBI6w',
    appId: '1:1023352143949:android:815399838c7235671d1c04',
    messagingSenderId: '1023352143949',
    projectId: 'untitled-7441b',
    storageBucket: 'untitled-7441b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATQumhwfpebryR0dKhynJ4fMNYHu14QK8',
    appId: '1:1023352143949:ios:5dd74abeec771f3e1d1c04',
    messagingSenderId: '1023352143949',
    projectId: 'untitled-7441b',
    storageBucket: 'untitled-7441b.appspot.com',
    iosClientId: '1023352143949-uud6bakcspnkr75lg5vsjg0sb0br2l3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp',
  );
}
